services:
  db:
    image: postgres:latest
    container_name: ecotasty-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ecotasty
      POSTGRES_PASSWORD: ecotasty
      POSTGRES_DB: ecotastydb

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: ecotasty-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  mongo:
    image: mongo:latest
    container_name: ecotasty-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecotasty
      MONGO_INITDB_ROOT_PASSWORD: ecotasty

  mongo-express:
    image: mongo-express:latest
    container_name: ecotasty-mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ecotasty
      ME_CONFIG_BASICAUTH_PASSWORD: ecotasty
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ecotasty
      ME_CONFIG_MONGODB_ADMINPASSWORD: ecotasty
      ME_CONFIG_MONGODB_SERVER: mongo

    depends_on:
      - mongo
